@startuml

left to right direction

entity customer {
    * id : number <<generated>>
    --
    * name : varchar
}

entity account {
    * id : number <<generated>>
    --
    * name : varchar
}

entity customer_accounts {
    * id : number <<generated>>
    --
    * account_id : number
    * customer_id : number
}

entity product {
    * id : number <<generated>>
    --
    * price : number
    * stock_keeping_unit : varchar
}

entity shopping_basket_line_item {
    * account_id : number
    * product_id : number
    --
    * quantity : number
}

entity payment_card {
    * id : number <<generated>>
    --
    * name : varchar
    * cardholder_name : varchar
    * card_number : varchar
    * expiry : date
    * account_id : number
}

entity order {
    * id : number <<generated>>
    --
    * creation_time : timestamp
    * payment_card_id : number
    * order_state : varchar
    * account_id : number
}

entity order_line_item {
    * order_id : number
    * product_id : number
    --
    * quantity : number
    * unit_price : number
}

entity author {
    * id : number <<generated>>
    --
    * name : varchar
    alias : varchar
}

entity book {
    * product_id : number
    --
    * title : varchar
    production_credits : varchar
    summary : varchar
    language : varchar
    subject : varchar
}

entity book_authors {
    * book_id : number
    * author_id : number
    --
}

customer::id ||--|{ customer_accounts::customer_id
customer_accounts::account_id }|--|| account::id
account::id ||--o{ shopping_basket_line_item::account_id
shopping_basket_line_item::product_id }o--|| product::id
account::id ||--o{ payment_card::account_id
account::id ||--o{ order::account_id
order::id ||--|{ order_line_item::order_id
order::payment_card_id }o--|| payment_card::id
order_line_item::product_id }o--|| product::id
product::id ||--o| book::product_id
book::product_id ||--|{ book_authors::book_id
book_authors::author_id }|--|| author::id

@enduml
