@startuml

interface Product {
    String stockKeepingUnit
    long price
}

' Based on Project Gutenberg agent
class Author {
    String name
    String alias
    LocalDate birthdate
}

class Book {
    String title
    Author author
    ' https://www.loc.gov/marc/bibliographic/bd508.html
    String productionCredits
    ' https://www.loc.gov/marc/bibliographic/bd520.html
    String summary
    String language
    String subject
}

Product <|.. Book
Book::author "*" --> "1..*" Author

class OrderLineItem {
    Product item
    int quantity
}

OrderLineItem::item "*" --> "1" Product

class ShoppingBasket {
    List orderLineItems

    addItem(Product product)
    removeItem(OrderLineItem orderLineItem)
    updateItemQuantity(OrderLineItem orderLineItem, int quantity)
}

ShoppingBasket::orderLineItems "1" *-> "*" OrderLineItem

class PaymentCard {
    String cardNumber
    LocalDate expiryDate
}

class Order {
    Instant timestamp
    List orderLineItems
    PaymentCard paymentCard
}

Order::orderLineItems "1" *-> "*" OrderLineItem
Order::paymentCard "*" --> "1" PaymentCard

class Account {
    List orders
}

Account::orders "*" --> Order

class User {
    Account account
}
User::account "1" *--> "1" Account

@enduml