@startuml

abstract class Product {
    String stockKeepingUnit
    long price
}

' Based on Project Gutenberg agent
class Author {
    String name
    String alias
}

class Book {
    String title
    ' https://www.loc.gov/marc/bibliographic/bd508.html
    String productionCredits
    ' https://www.loc.gov/marc/bibliographic/bd520.html
    String summary
    String language
    String subject
}

Product <|-- Book
Book "*" --> "authors 1..*" Author

class ShoppingBasketLineItem {
    int quantity
}

ShoppingBasketLineItem "*" --> "product 1" Product

note as N1
    ShoppingBasketLineItem does not include
    the product unit price which means the
    product price may change until the order
    is created.
endnote
N1 ... ShoppingBasketLineItem

class ShoppingBasket {
    addItem(Product product)
    removeItem(OrderLineItem orderLineItem)
    updateItemQuantity(OrderLineItem orderLineItem, int quantity)
}

ShoppingBasket "1" *--> "lineItems *" ShoppingBasketLineItem

class PaymentCard {
    String cardNumber
    LocalDate expiryDate
}

class OrderLineItem {
    int quantity
    long unitPrice
}

OrderLineItem "*" --> "product 1" Product

note as N2
    OrderLineItem unitPrice records the product
    price at the point where the order was made
    so changes to the product price during order
    processing will not result in unexpected
    payments.
endnote
N2 ... OrderLineItem

enum OrderState {
    WAITING
    PROCESSING
    DISPATCHED
    CANCELLED
}

class Order {
    Instant creationTimestamp
}

Order *--> "orderState 1" OrderState
Order "1" *--> "lineItems 1..*" OrderLineItem
Order "*" --> "paymentCard 1" PaymentCard

class Account {
}

Account "1" --> "orders *" Order
Account "1" *--> "paymentCard *" PaymentCard

class User {
    String name
}
User "1" *--> "account 1" Account

@enduml